name: CMake Build Matrix

on:
  push:
    branches: build

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      BUILD_ARCH: ${{ matrix.config.arch }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        config:
        - {
            name: "Windows 64",
            os: windows-2019,
            arch: x64,
            python-arch: x64,
          }
        - {
            name: "Windows 32",
            os: windows-2019,
            arch: Win32,
            python-arch: x86,
          }
        - {
            name: "macOS 10.15",
            os: macos-10.15,
            arch: x64,
            python-arch: x64,
          }

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name:  Build Windows
      if: runner.os == 'Windows'
      shell: bash
      run:   |
        mkdir build
        cd $GITHUB_WORKSPACE\\build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -A $BUILD_ARCH ..

        cmake --build . --config $BUILD_TYPE -j 2

    - name:  Build MacOS
      if: runner.os == 'macos'
      shell: bash
      run:   |
        mkdir build
        cd $GITHUB_WORKSPACE/build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j2


